### ISSUE TITLE
编译时遇到问题

### ISSUE THREAD

**Issue by MCredbear** [linuxdeepin/go-gir#2]
这是我的log:
'
firefly@firefly:/media/firefly/dde/go-gir$ dpkg-buildpackage
dpkg-buildpackage: info: source package golang-github-linuxdeepin-go-gir
dpkg-buildpackage: info: source version 1.0.1-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Deepin Packages Builder <packages@deepin.com>
dpkg-buildpackage: info: host architecture arm64
 dpkg-source --before-build .
 fakeroot debian/rules clean
dh clean --buildsystem=golang --with=golang
   dh_auto_clean -O--buildsystem=golang
   dh_autoreconf_clean -O--buildsystem=golang
   dh_clean -O--buildsystem=golang
 dpkg-source -b .
dpkg-source: info: using source format '1.0'
dpkg-source: warning: source directory 'go-gir' is not <sourcepackage>-<upstreamversion> 'golang-github-linuxdeepin-go-gir-1.0.1'
dpkg-source: info: building golang-github-linuxdeepin-go-gir in golang-github-linuxdeepin-go-gir_1.0.1-1.tar.gz
dpkg-source: info: building golang-github-linuxdeepin-go-gir in golang-github-linuxdeepin-go-gir_1.0.1-1.dsc
 debian/rules build
dh build --buildsystem=golang --with=golang
   dh_update_autotools_config -O--buildsystem=golang
   dh_autoreconf -O--buildsystem=golang
   dh_auto_configure -O--buildsystem=golang
   dh_auto_build -O--buildsystem=golang
        cd obj-aarch64-linux-gnu && go install -gcflags=all=\"-trimpath=/media/firefly/dde/go-gir/obj-aarch64-linux-gnu/src\" -asmflags=all=\"-trimpath=/media/firefly/dde/go-gir/obj-aarch64-linux-gnu/src\" -v -p 4 github.com/linuxdeepin/go-gir/atk-1.0 github.com/linuxdeepin/go-gir/cairo-1.0 github.com/linuxdeepin/go-gir/flatpak-1.0 github.com/linuxdeepin/go-gir/gdk-3.0 github.com/linuxdeepin/go-gir/gdkpixbuf-2.0 github.com/linuxdeepin/go-gir/gio-2.0 github.com/linuxdeepin/go-gir/glib-2.0 github.com/linuxdeepin/go-gir/gobject-2.0 github.com/linuxdeepin/go-gir/gtk-3.0 github.com/linuxdeepin/go-gir/gudev-1.0 github.com/linuxdeepin/go-gir/pango-1.0 github.com/linuxdeepin/go-gir/util
errors
internal/cpu
internal/race
runtime/internal/atomic
runtime/internal/sys
sync/atomic
math/bits
math
internal/bytealg
internal/testlog
unicode/utf8
unicode
runtime
runtime/cgo
strconv
sync
io
reflect
syscall
github.com/linuxdeepin/go-gir/cairo-1.0
internal/syscall/unix
time
internal/poll
github.com/linuxdeepin/go-gir/util
os
fmt
github.com/linuxdeepin/go-gir/glib-2.0
github.com/linuxdeepin/go-gir/gobject-2.0
github.com/linuxdeepin/go-gir/atk-1.0
github.com/linuxdeepin/go-gir/pango-1.0
github.com/linuxdeepin/go-gir/gudev-1.0
github.com/linuxdeepin/go-gir/gio-2.0
# github.com/linuxdeepin/go-gir/gudev-1.0
/usr/bin/ld: //usr/lib/aarch64-linux-gnu/libgio-2.0.so.0: undefined reference to `g_build_filename_valist'
/usr/bin/ld: //usr/lib/aarch64-linux-gnu/libgio-2.0.so.0: undefined reference to `g_spawn_async_with_fds'
/usr/bin/ld: //usr/lib/aarch64-linux-gnu/libgio-2.0.so.0: undefined reference to `g_canonicalize_filename'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
# github.com/linuxdeepin/go-gir/atk-1.0
/usr/bin/ld: /usr/bin/../lib/gcc/aarch64-linux-gnu/8/../../../aarch64-linux-gnu/libatk-1.0.so: undefined reference to `g_log_structured_standard'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
# github.com/linuxdeepin/go-gir/pango-1.0
/usr/bin/ld: /usr/bin/../lib/gcc/aarch64-linux-gnu/8/../../../aarch64-linux-gnu/libpango-1.0.so: undefined reference to `g_log_structured_standard'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
^Cmake: *** [debian/rules:4: build] Error 1
dpkg-buildpackage: error: debian/rules build subprocess was killed by signal 2
firefly@firefly:/media/firefly/dde/go-gir$
'
系统:debian sid arm64

**Comment by MCredbear** [comment]
用gcc编译也是一样的，有解吗？

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
